### PR TITLE
Update 1dsfm sampling type

### PR DESCRIPTION
**Pull request by akshay-krishnan**
This PR updates the sampling strategy in 1dsfm to reduce the randomness in the outlier rejection step.

### CODE REVIEW

**Comment by akshay-krishnan** [comment]
Translation averaging metrics after this change: 
newplot

**Comment by akshay-krishnan** [comment]
BA metrics:
newplot (1)

**Comment by akshay-krishnan** [comment]
This change is required to ensure determinism of translation averaging but looks like it produces regressions in TA and BA metrics, particularly on the skydio32 dataset. Not sure if we should proceed with this.

**Comment by travisdriver** [comment]
> This change is required to ensure determinism of translation averaging but looks like it produces regressions in TA and BA metrics, particularly on the skydio32 dataset. Not sure if we should proceed with this.


Have you tried tuning the outlier threshold? According to the dashboard, it seems that 1DSfM is accepting more (potentially outlier) measurements than before. Maybe we should make the threshold more restrictive?

**Comment by johnwlambert** [comment]
Good points Travis. It looks like maybe the regression is significant enough that we should investigate a bit more.

Would the KDE be more deterministic?

**Comment by akshay-krishnan** [comment]
> Have you tried tuning the outlier threshold? According to the dashboard, it seems that 1DSfM is accepting more (potentially outlier) measurements than before. Maybe we should make the threshold more restrictive?

That is only the case for SIFT-skydio32. For all the others it is rejecting more measurements (note the increase in outliers and the drop in recall).

**Comment by akshay-krishnan** [comment]
> Good points Travis. It looks like maybe the regression is significant enough that we should investigate a bit more.
> 
> Would the KDE be more deterministic?

KDE also does not pass @ayushbaid 's reproducibility tests.

**Comment by travisdriver** [comment]
> > Have you tried tuning the outlier threshold? According to the dashboard, it seems that 1DSfM is accepting more (potentially outlier) measurements than before. Maybe we should make the threshold more restrictive?
> 
> That is only the case for SIFT-skydio32. For all the others it is rejecting more measurements (note the increase in outliers and the drop in recall).

Yeah sorry I meant the other way around. You should try _relaxing_ the threshold.

**Comment by akshay-krishnan** [comment]
I found slightly better results with a threshold of 0.125, but this is still a regression compared to master. 

translation averaging metrics: 
newplot (2)

**Comment by akshay-krishnan** [comment]
bundle adjustment metrics
newplot (3)

**Comment by akshay-krishnan** [comment]
I am also not too sure about these numbers, looking at the result poses for skydio-32, they look bad both on master as well as the new branch..

**Comment by akshay-krishnan** [comment]
@johnwlambert  @travisdriver  please let me know if the PR looks good to be merged. was there anything else to be checked?

**Review by ayushbaid — APPROVED** [review]
Palace-of-fine-arts dataset has a huge improvement. Any speculation on why that might be the case?

**Comment by akshay-krishnan** [comment]
I would not consider that one, the frontend outputs between baseline and test are not the same.

**Review by travisdriver — APPROVED** [review]
LGTM!

**Pull request merged**
