### PR TITLE
Support configuring Shonan uncertainty from config

### PR DESCRIPTION
**Pull request by johnwlambert**
Add support to allow configuring Shonan uncertainty from a config.

### CODE REVIEW

**Comment by travisdriver** [comment]
Could you add the uncertainty to the config file?

**Comment by awayfromdog1** [comment]
> Could you add the uncertainty to the config file?

Thanks for the review @travisdriver. In a follow up PR we will be able to tune this from config.

I’d prefer to keep some default value here for now in case people forget to specify it in the config.

**Comment by johnwlambert** [comment]
> Could you add the uncertainty to the config file?

Thanks for the review @travisdriver. In a follow up PR we will be able to tune this from config.

I’d prefer to keep some default value here for now in case people forget to specify it in the config

**Review by akshay-krishnan — APPROVED** [review]
would be nice to have it in config, can be done in another PR

**Comment by travisdriver** [comment]
> > Could you add the uncertainty to the config file?
> 
> 
> 
> Thanks for the review @travisdriver. In a follow up PR we will be able to tune this from config.
> 
> 
> 
> I’d prefer to keep some default value here for now in case people forget to specify it in the config

You can keep a default value in the constructor, I was just saying it would be nice to expose it in the config since I thought that's what the PR title implied.

**Pull request merged**
