### PR TITLE
adding pylint to CI

### PR DESCRIPTION
**Pull request by ayushbaid**
Adding the pylint lint check to the CI

### CODE REVIEW

**Comment by johnwlambert** [comment]
Thanks for the PR, @ayushbaid. What does pylint check for, that `black` and `flake8` dont catch?

It looked like most of the warnings it raised in the CI run were false alarms, so I'm a bit averse to adding this.

**Comment by akshay-krishnan** [comment]
Yeah, could you let me know what it’s doing? Not much code to review anyway.

**Comment by ayushbaid** [comment]
I do not understand it completely, but it looks like pylint is a superset of the flake8 checks. It is more thorough (and slow), and somewhat outdated too.

Pylint is more popular than flake8 though.

References:
1. https://www.reddit.com/r/Python/comments/82hgzm/any_advantages_of_flake8_over_pylint/

**Comment by johnwlambert** [comment]
I see. I would prefer to not merge this unless there is a clear and compelling use case over flake8 and black.

I looked through several dozen of the pylint errors in CI and they all looked to be raising false alarms, so I'd consider it to not be helpful as used presently.

**Pull request closed without merging**
