### PR TITLE
Add assert_all_results to repro test base

### PR DESCRIPTION
**Pull request by akshay-krishnan**
Adding an optional method to the repro test base class to check statistics on all results. This is useful for translation averaging.

### CODE REVIEW

**Review by ayushbaid — COMMENTED** [review]
The idea looks good.

However, I do not agree with the name `assert_all_results`. What kind of comparisons do we think are possible. I think percentile based checks are what we need right now, `__assert_percentile_of_results` or something of similar fashion is better?

**Comment by akshay-krishnan** [comment]
It does not have to be percentile, cant we leave that bit to the user? Maybe they use mean, std? For example, in translation averaging I am checking standard deviation.

**Comment by akshay-krishnan** [comment]
I am open to other names though.

**Comment by akshay-krishnan** [comment]
`assert_results_statistics` ? I dont know ..

**Comment by ayushbaid** [comment]
> 

`assert_results_statistics` looks good. The other alternative is to let the one function remain, and the individual tests can override as needed. For example, the T.A. test can override the current method and check for std deviations instead of equality for each result.

**Comment by akshay-krishnan** [comment]
Yeah, but then no logic from the base class would be used. Thought it would be nice to have some common structure. And lesser code in derived class. But Im fine with either option.

**Review by johnwlambert — APPROVED** [review]
LGTM, thanks Akshay

**Pull request merged**
