### PR TITLE
Use `align_robust` from Colmap to align reconstructions

### PR DESCRIPTION
**Pull request by ayushbaid**
`align_robust` offers a robust alignment mechanism to align a reconstruction to list of camera positions (no orientation), which looks to work better than GTSFM's logic

### CODE REVIEW

**Review by travisdriver — APPROVED** [review]
LGTM

**Comment by travisdriver** [comment]
> `align_robust` offers a robust alignment mechanism to align a reconstruction to list of camera positions (no orientation), which looks to work better than GTSFM's logic

Does this mean it doesn't fit to orientation?

**Comment by ayushbaid** [comment]
> > `align_robust` offers a robust alignment mechanism to align a reconstruction to list of camera positions (no orientation), which looks to work better than GTSFM's logic
> 
> Does this mean it doesn't use orientation as all to compute the Sim(3)?

Yep looks like that.

**Comment by ayushbaid** [comment]
> > > `align_robust` offers a robust alignment mechanism to align a reconstruction to list of camera positions (no orientation), which looks to work better than GTSFM's logic
> > 
> > 
> > Does this mean it doesn't use orientation as all to compute the Sim(3)?
> 
> Yep looks like that.

Atleast not absolute wTis. Maybe it uses relative rotations

**Pull request merged**
