### PR TITLE
Add a benchmark for Notre-Dame-20

### PR DESCRIPTION
**Pull request by johnwlambert**
20 upright images from different cameras from Phototourism project, around Notre Dame Cathedral.

This dataset is good for debugging DA errors since all points should really be just on one plane (the cathedral's facade).

### CODE REVIEW

**Review by akshay-krishnan — APPROVED** [review]
At what point do we say we're overloading the CI?  :)

**Comment by travisdriver** [comment]
Would you mind adding a picture of the final reconstruction results for reference if you get the chance?

**Comment by johnwlambert** [comment]
> At what point do we say we're overloading the CI? :)

We get 6 wall clock hours for free , and it looks like our 8 CI runs currently take just 3 hours 50 min in wall clock time. So I think we can continue to overload it : - )

**Comment by johnwlambert** [comment]
Screen Shot 2021-09-20 at 11 52 17 AM
Screen Shot 2021-09-20 at 11 52 09 AM
Screen Shot 2021-09-20 at 11 52 05 AM
Screen Shot 2021-09-20 at 11 52 01 AM

**Comment by johnwlambert** [comment]
Metrics from SG + LoRANSAC with exhaustive search over all 20 frames w/ the controller. very concerning that we get translation direction errors of 10-80 degrees even after cycle consistency. 

Screen Shot 2021-09-20 at 11 57 44 AM
:
Screen Shot 2021-09-20 at 11 57 54 AM
Screen Shot 2021-09-20 at 11 58 08 AM

Screen Shot 2021-09-20 at 11 58 48 AM
Screen Shot 2021-09-20 at 11 58 52 AM

**Pull request merged**
