### PR TITLE
[WIP] use kde for translation averaging

### PR DESCRIPTION
**Pull request by johnwlambert**

### CODE REVIEW

**Comment by akshay-krishnan** [comment]
Had to close and re-open the PR for my commits to show up. Not sure why.

**Comment by akshay-krishnan** [comment]
Update: it looks like simpling switching the sampling method also does not fix the randomness on _all_ datasets, although it does improve for some. There is one edge on skydio8 that seems to be close to the inlier-outlier decision boundary. I should examine those weights and thresholds further.

**Comment by travisdriver** [comment]
It looks like the workflow didn't run either; you may want to try closing and reopening again.

**Comment by johnwlambert** [comment]
Workflow wasn't running, changes present in https://github.com/borglab/gtsfm/pull/445 now.

**Pull request closed without merging**
