### PR TITLE
Adding Skydio 2 to sensor database

### PR DESCRIPTION
**Pull request by womackj1**

### CODE REVIEW

**Comment by johnwlambert** [comment]
Thanks for the PR, @womackj1. Do you mind posting here a summary of where you got the values from? And what the EXIF looks like from the camera?

**Comment by womackj1** [comment]
The values come from here:
[Skydio 2 Primary Camera System](https://www.skydio.com/skydio-2)
Lens Focal Length: 20mm (35mm format equivalent)
Should I add the rest of this sensor's info to sensor_database_detailed.csv?

EXIF as stored in the Image class:
{'ExifVersion': b'0230', 'ComponentsConfiguration': b'\x01\x02\x03\x00', 'ShutterSpeedValue': 11.06, 'ApertureValue': 2.97, 'DateTimeDigitized': '2021:02:06 23:39:37', 'BrightnessValue': 6.15, 'ExposureBiasValue': 0.0, 'MaxApertureValue': 2.97, 'MeteringMode': 1, 'LightSource': 20, 'Flash': 32, 'FocalLength': 3.7, 'ColorSpace': 1, 'ExifImageWidth': 4056, 'ExifInteroperabilityOffset': 695, 'ImageWidth': 4056, 'ExifImageHeight': 3040, 'ImageLength': 3040, 'Make': 'Skydio', 'Model': '2', 'Orientation': 1, 'YCbCrPositioning': 1, 'SensingMethod': 0, 'XResolution': 72.0, 'YResolution': 72.0, 'SceneType': b'\x01', 'ImageUniqueID': '6A3B3326-7484-483C-B8E4-36CA74F64DB7', 'ExposureProgram': 2, 'GPSInfo': {0: b'\x02\x03\x00\x00', 1: 'N', 2: (37.0, 45.718338, 0.0), 3: 'W', 4: (122.0, 23.214402, 0.0), 5: b'\x00', 6: 19.797, 8: '20', 12: 'K', 13: 0.262, 14: 'T', 15: 31.678, 16: 'T', 17: 91.989, 27: b'ASCII\x00\x00\x00GPS+Vision', 31: 0.486}, 'ISOSpeedRatings': 100, 'ResolutionUnit': 2, 'ExposureMode': 0, 'FlashPixVersion': b'0100', 'WhiteBalance': 0, 'BodySerialNumber': '096251606804132', 'Software': '2208471ee1874f779b381987fa1f0ac7', 'DateTime': '2021:02:06 23:39:37', 'FocalLengthIn35mmFilm': 21, 'ExifOffset': 202, 'ExposureTime': 0.000468384074941452, 'FNumber': 2.8}

EXIF as displayed in Finder:
Last opened: April 20, 2021 at 9:57 AM
Dimensions: 4056 × 3040
Device make: Skydio
Device model: 2
Color space: RGB
Color profile: sRGB IEC61966-2.1
Focal length: 3.7 mm
Alpha channel: No
Red eye: No
Metering mode: Average
F number: f/2.8
Exposure program: Normal
Exposure time: 1/2,705
Latitude: 37° 45' 43.02" N
Longitude: 122° 23' 12.834" W

**Comment by johnwlambert** [comment]
Hi @womackj1, what we are looking for is CCD width, but I don’t see it here. I saw you listed the sensor width as 35mm, but i don’t see that listed anywhere on the spec sheet or in the EXIF.

http://phototour.cs.washington.edu/focal.html

https://www.easybasicphotography.com/35mm-equivalent.html

https://en.m.wikipedia.org/wiki/35_mm_equivalent_focal_length

it’s possible the CCD width of Skydio 2 is not publicly available @dellaert

**Comment by ayushbaid** [comment]
They say which sensor they use: "Skydio 2 features an all-new, best-in-class camera, meticulously perfected around Sony's IMX577 sensor"

Ref: https://www.skydio.com/skydio-2

**Comment by ayushbaid** [comment]
@womackj1 can you check the sensor width for the mentioned sensor.

**Comment by womackj1** [comment]
"Sony has four 12MP sensors for 1/2.3". There is the IMX277, IMX577, IMX477 and IMX377." from [dpreview](https://www.dpreview.com/forums/post/62685445) .

I updated the sensor database entry for Skydio to 6.17mm using the following [conversion](https://en.wikipedia.org/wiki/Image_sensor_format) from ratio of inches to mm.

**Comment by ayushbaid** [comment]
This link points to some other value: https://www.sony-semicon.co.jp/products/common/pdf/IMX577-AACK_Flyer.pdf

@johnwlambert

**Comment by johnwlambert** [comment]
Hi Jonathan, thanks for the updates. It looks like something has gone wrong with the PR history -- can you try merging in master again? It says 15 files have changed.

Otherwise, I would just create a fresh branch of master -- I think just 1 file should be changed here

**Comment by johnwlambert** [comment]
Correct me if I'm wrong @ayushbaid @womackj1 , but the value here should be 6.286 mm. Jon I believe you put 6.17 mm.

Every pixel on the sensor unit occupies 1.55 micrometers x 1.55 micrometers. If you lay out 3040 of them along one dim, you get 4.712 mm, and 4056 of them will give you

3040 * 1.55 = 4.712 mm
4056 * 1.55 = 6286.8 mm

That diagonal would be `sqrt( 4.712**2 + 6.2868**2 ) = 7.857` by Pythagorean

7.857 is confirmed here: https://www.gophotonics.com/products/cmos-image-sensors/sony-corporation/21-209-imx577 and  https://www.sony-semicon.co.jp/products/common/pdf/IMX577-AACK_Flyer.pdf

1.55 micrometer pixels per https://www.sony-semicon.co.jp/products/common/pdf/IMX577-AACK_Flyer.pdf and https://www.framos.com/media/pdf/23/70/ae/g9cLCD2tqPgF8FWzdDQplbmRzdHJlYW0NCmVuZG9iag0KeHJlZg0KMCA3NDANCjAwMDAwMDAwODUgNjU1MzUgZg0KMDAwMDAwMDAxNyAwMDAwMCBuDQowMDAwMDAwMTY4IDAwMDAwIG4NCjAwMDAwMDAyMzggMDAwMDAgbg0KMDAwMDAwMDc.pdf

**Comment by johnwlambert** [comment]
`focal_length_px = max(img_h_px, img_w_px) * focal_length_mm / sensor_width_mm`

`f_px = 2387 px = 4056 px * 3.7 mm / 6.2868 mm`

@womackj1 does 2387 px check out with what COLMAP spits out as the optimized focal length for this sequence?

**Comment by johnwlambert** [comment]
I see that 6.17 is given as the reference for the 1/2.3 cameras here https://en.wikipedia.org/wiki/Image_sensor_format#Table_of_sensor_formats_and_sizes i.e. for (1/2.3" (Pentax Q, Sony Cyber-shot DSC-W330, GoPro HERO3, Panasonic HX-A500, Google Pixel/Pixel+, DJI Phantom 3[42]/Mavic 2 Zoom[43]), Nikon P1000/P900)

But the IMX557 diagonal is longer than the wikipedia reference (7.66 mm), so the width should be larger as well at the same aspect ratio

**Comment by womackj1** [comment]
2387 px checks out. The sensor database is updated with the sensor width value of 6.286.

**Comment by johnwlambert** [comment]
Merged in https://github.com/borglab/gtsfm/commit/93b01a6d54421d20bd56e17140be755ca7d6384a

**Pull request closed without merging**
