### PR TITLE
switching to DEGENSAC in benchmarks

### PR DESCRIPTION
**Pull request by ayushbaid**
This PR switches to degensac verifier instead of OpenCV's RANSAC

### CODE REVIEW

**Comment by ayushbaid** [comment]
# Skydio-32
Front-end metrics show improvement in quality, with less number of pairs having a result, but error going down.

<table>
<thead>
<tr><th>Metric name                                </th><th style="text-align: right;">    Baseline</th><th style="text-align: right;">    USAC </th><th style="text-align: right;">    Degensac </th></tr>
</thead>
<tbody>
<tr><td>angular_err_threshold_deg                  </td><td style="text-align: right;">  5      </td><td style="text-align: right;">  5      </td><td style="text-align: right;">  5      </td></tr>
<tr><td>num_total_image_pairs                      </td><td style="text-align: right;">496      </td><td style="text-align: right;">496      </td><td style="text-align: right;">496      </td></tr>
<tr><td>num_valid_image_pairs                      </td><td style="text-align: right;">119      </td><td style="text-align: right;"> 81      </td><td style="text-align: right;">149      </td></tr>
<tr><td>rotation_success_count                     </td><td style="text-align: right;"> 80      </td><td style="text-align: right;"> 66      </td><td style="text-align: right;">115      </td></tr>
<tr><td>translation_success_count                  </td><td style="text-align: right;"> 48      </td><td style="text-align: right;"> 42      </td><td style="text-align: right;"> 83      </td></tr>
<tr><td>pose_success_count                         </td><td style="text-align: right;"> 41      </td><td style="text-align: right;"> 40      </td><td style="text-align: right;"> 79      </td></tr>
<tr><td>num_all_inlier_correspondences_wrt_gt_model</td><td style="text-align: right;">  0      </td><td style="text-align: right;">  4      </td><td style="text-align: right;">  0      </td></tr>
<tr><td>mean_rot3_angular_errors_deg               </td><td style="text-align: right;">  6.27473</td><td style="text-align: right;">  4.00541</td><td style="text-align: right;">  5.16539</td></tr>
<tr><td>mean_trans_angular_errors_deg              </td><td style="text-align: right;"> 42.5209 </td><td style="text-align: right;"> 34.8134 </td><td style="text-align: right;"> 29.93   </td></tr>
<tr><td>mean_pose_errors_deg                       </td><td style="text-align: right;"> 43.2005 </td><td style="text-align: right;"> 35.1117 </td><td style="text-align: right;"> 30.5357 </td></tr>
</tbody>
</table>

The final output has a staggering 1715 tracks instead of 183 tracks in the baseline

**Review by akshay-krishnan — APPROVED** [review]

**Comment by akshay-krishnan** [comment]
Looks like a pretty good improvement. 
Unrelated to this PR, but Im curious what angular_err_threshold_deg is. 5 degrees is a pretty high number for a threshold.

**Comment by johnwlambert** [comment]
Thanks for the PR @ayushbaid. Can you compare SIFT + Degensac with SuperGlue + Ransac 5-pt or SuperGlue + Degensac?

I left SIFT out of all of the metrics (and made it not the default) since it was so much worse than SuperGlue.

**Comment by ayushbaid** [comment]
> Looks like a pretty good improvement.
> Unrelated to this PR, but Im curious what angular_err_threshold_deg is. 5 degrees is a pretty high number for a threshold.

Yep it is 5 degrees. I agree its a bit high but its an unreasonable number imo

**Comment by ayushbaid** [comment]
> Thanks for the PR @ayushbaid. Can you compare SIFT + Degensac with SuperGlue + Ransac 5-pt or SuperGlue + Degensac?
> 
> I left SIFT out of all of the metrics (and made it not the default) since it was so much worse than SuperGlue.

I am using SIFT because of the compute constraints, not from the Github side but our ease of development side. I think deep front end should be run on colab notebooks and the metrics posted on PRs. A simple SIFT based GTSFM takes 15 mins to run on the Github CI, and I dont think its feasible to run deep front end on a 2 core machine.

**Comment by johnwlambert** [comment]
> > Thanks for the PR @ayushbaid. Can you compare SIFT + Degensac with SuperGlue + Ransac 5-pt or SuperGlue + Degensac?
> > I left SIFT out of all of the metrics (and made it not the default) since it was so much worse than SuperGlue.
> 
> I am using SIFT because of the compute constraints, not from the Github side but our ease of development side. I think deep front end should be run on colab notebooks and the metrics posted on PRs. A simple SIFT based GTSFM takes 15 mins to run on the Github CI, and I dont think its feasible to run deep front end on a 2 core machine.

@ayushbaid agreed that SG is much slower. But the performance was much, much better. Can we test it out just to see how long it would take in CI?

**Comment by johnwlambert** [comment]
I think the benchmark has to be of our best configuration to be meaningful about future development

**Comment by ayushbaid** [comment]
> I think the benchmark has to be of our best configuration to be meaningful about future development

Agreed. I think I can create two benchmark jobs. One for SIFT and one for Deep?

**Comment by johnwlambert** [comment]
2 benchmark jobs sounds good to me.

**Comment by johnwlambert** [comment]
Hi @ayushbaid, I think we should go ahead and close this now? Since we found better performance from both LORANSAC and USAC than DEGENSAC?

**Comment by johnwlambert** [comment]
the skydio-32 result table here looks different than in the other PR -- what was the change there?

**Comment by ayushbaid** [comment]
> the skydio-32 result table here looks different than in the other PR -- what was the change there?

This was using the SIFT front-end and hence poor results.

**Pull request closed without merging**
