### PR TITLE
Add `max_keypoints` to config

### PR DESCRIPTION
**Pull request by travisdriver**

### CODE REVIEW

**Comment by johnwlambert** [comment]
Hi Travis, since we're modifying the behavior of the default configs, can you post the dashboard to show how performance changes?

**Review by ayushbaid — APPROVED** [review]
Approved pending metrics comparison

**Comment by travisdriver** [comment]
@johnwlambert It doesn't modify any of the default behavior, just exposing the `max_keypoints` attribute to the config. Here are the results (changes are due to randomness in output as identified in #323)

newplot (4)

**Review by johnwlambert — APPROVED** [review]
LGTM, thanks

**Pull request merged**
