### PR TITLE
Add isort to automatically sort imports

### PR DESCRIPTION
**Pull request by kfu02**
As described [here](https://pycqa.github.io/isort/index.html), isort will automatically sort Python imports according to the Google [style guide](https://google.github.io/styleguide/pyguide.html#313-imports-formatting) (alphabetized, std lib imports first, etc.). This can be run the same way as black, e.g. `isort -l 120 gtsfm/ tests/`.

Here I've
* added isort to the dependency list
* updated the contributing guide
* run isort on all files in `gtsfm/` and `tests/`

### CODE REVIEW

**Comment by johnwlambert** [comment]
Looks great. I think there is a conflict with `python black`, though. Can you run `black gtsfm -l 120` once more on the entire `gtsfm` directory, after running `isort`?

**Comment by kfu02** [comment]
> Looks great. I think there is a conflict with `python black`, though. Can you run `black gtsfm -l 120` once more on the entire `gtsfm` directory, after running `isort`?

You're right, I forgot the `--profile black` flag on `isort`, fixed now. (See docs [here](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html).)

**Comment by johnwlambert** [comment]
Looks good. Do you mind pulling in `master` to resolve the merge conflicts?

**Review by johnwlambert — APPROVED** [review]
Thanks, feel free to merge

**Pull request merged**
