### PR TITLE
Disabling skydio-501

### PR DESCRIPTION
**Pull request by ayushbaid**
Disabling skydio 501 for quicker turnaround on the CI

### CODE REVIEW

**Comment by dellaert** [comment]
If we can make good decisions on merging PRs without this dataset, maybe it *is* a good idea to turn off until after Hilti...

**Review by dellaert — APPROVED** [review]
I will stop CI on this an merge immediately.

**Comment by ayushbaid** [comment]
Thanks Frank!

**Comment by dellaert** [comment]
> Thanks Frank!

Still interested in answer to question: why are we *saving* a lot of images? And can we turn that off, for *all* benchmark runs?

**Comment by ayushbaid** [comment]
We are not sharing images of 2-view correspondences. There should be just
plots of poses and landmarks. <10 I think. Let me check again.

**Comment by dellaert** [comment]
Maybe it *was* downloading the dataset to the compute node.

**Pull request merged**
